[tool.poetry]
name = "ftxcoinstaker"
version = "0.1.0"
description = "High Frequency Trading on FTX"
authors = ["David Lehuby <david.lehuby@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
ftx = "^1.0.2"
ciso8601 = "^2.1.3"

[tool.poetry.dev-dependencies]
pylint = "^2.7.2"
autopep8 = "^1.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ftxcoinstaker = "ftxcoinstaker.main:main"
